### ISSUE TITLE
建议：增加密钥功能，生成分段的随机密钥并在服务端验证

### ISSUE THREAD

**Issue by ghost** [fucklinux/fakeCAPTCHA#1]
这个项目很有意思（doge
然后我想到了一些增强模拟真实性的功能，就是增加密钥值，
可以在验证完成后赋予html元素值，然后在提交表单与后端api通讯的时候读取值并添加进去，
就像真实的验证码一样，

密钥也可以有简单的验证功能：
在服务端或客户端模拟一个验证机制，即：
从接收到的密钥中提取出原始值（第一部分），计算其 MD5 并验证该结果是否与第二部分匹配
这样就能够模拟一个真实的验证码验证逻辑，增加真实性。

举个例子，
成功验证后生成随机的密钥 key = "12345678".
将密钥分为第一部分 = "12345678" 和第二部分 = MD5("12345678").
将密钥组合为 12345678|<md5_result> 并设置为元素的值。

当客户端提交表单时，可以在服务端对该密钥进行验证，验证MD5第一部分是否等于第二部分。

只是突发的一个想法（

**Comment by Huchangzhi** [comment]
这个项目只是一个伪验证码项目吧，没必要做的复杂，只起到最基本最简单的功能就行了

**Comment by ghost** [comment]
好的👍
